#!/usr/bin/env python3
"""Build the fixed re-entry nominal profile and GUI background from flight logs."""

from __future__ import annotations

import argparse
import csv
import math
import statistics
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont


KERBIN_RADIUS_M = 600_000.0
STANDARD_GRAVITY = 9.81
ENERGY_MIN_M = 110_000.0
ENERGY_MAX_M = 285_000.0
RANGE_MAX_M = 1_100_000.0
ENERGY_STEP_M = 5_000.0
MINIMUM_CORRIDOR_HALF_WIDTH_M = 25_000.0

IMAGE_WIDTH = 744
IMAGE_HEIGHT = 539
LAYOUT_HEIGHT = 380
PLOT_LEFT = 50.0
PLOT_RIGHT = 700.0
PLOT_TOP = 94.0
PLOT_BOTTOM = 314.0


def parse_number(row: dict[str, str], key: str) -> float:
    try:
        return float(row[key])
    except (KeyError, TypeError, ValueError):
        return math.nan


def surface_distance(row: dict[str, str]) -> float:
    lat1 = math.radians(parse_number(row, "latitude"))
    lon1 = math.radians(parse_number(row, "longitude"))
    lat2 = math.radians(parse_number(row, "target_latitude"))
    lon2 = math.radians(parse_number(row, "target_longitude"))
    cosine = (
        math.sin(lat1) * math.sin(lat2)
        + math.cos(lat1) * math.cos(lat2) * math.cos(lon2 - lon1)
    )
    return KERBIN_RADIUS_M * math.acos(max(-1.0, min(1.0, cosine)))


def load_curve(flight_directory: Path) -> list[tuple[float, float]]:
    flight_csv = flight_directory / "flight.csv"
    with flight_csv.open(newline="") as stream:
        rows = csv.DictReader(stream)
        points = []
        for row in rows:
            if row.get("step") != "reentry_low":
                continue
            altitude = parse_number(row, "altitude")
            speed = parse_number(row, "airspeed")
            remaining_range = surface_distance(row)
            energy_height = altitude + speed * speed / (2 * STANDARD_GRAVITY)
            if all(math.isfinite(value) for value in (energy_height, remaining_range)):
                points.append((energy_height, remaining_range))
    if len(points) < 2:
        raise ValueError(f"{flight_csv} has no usable reentry_low trajectory")
    points.sort()
    return points


def interpolate(points: list[tuple[float, float]], energy_height: float) -> float | None:
    if energy_height < points[0][0] or energy_height > points[-1][0]:
        return None
    for index in range(1, len(points)):
        energy0, range0 = points[index - 1]
        energy1, range1 = points[index]
        if energy0 <= energy_height <= energy1:
            if energy1 == energy0:
                return (range0 + range1) / 2
            fraction = (energy_height - energy0) / (energy1 - energy0)
            return range0 + (range1 - range0) * fraction
    return None


def build_profile(curves: list[list[tuple[float, float]]]) -> list[tuple[float, float, float]]:
    profile = []
    energy_height = ENERGY_MIN_M
    while energy_height <= ENERGY_MAX_M + 0.1:
        ranges = [interpolate(curve, energy_height) for curve in curves]
        ranges = [value for value in ranges if value is not None]
        if len(ranges) >= math.ceil(len(curves) / 2):
            nominal = statistics.median(ranges)
            observed_half_width = (max(ranges) - min(ranges)) / 2
            half_width = max(MINIMUM_CORRIDOR_HALF_WIDTH_M, observed_half_width)
            profile.append((energy_height, nominal, half_width))
        energy_height += ENERGY_STEP_M
    if len(profile) < 2:
        raise ValueError("Flights do not overlap the configured energy-height scale")
    return profile


def ks_list(values: list[float]) -> str:
    return "list(" + ",".join(str(round(value, 3)) for value in values) + ")"


def write_profile(path: Path, profile: list[tuple[float, float, float]], sources: list[Path]) -> None:
    energies = [point[0] for point in profile]
    ranges = [point[1] for point in profile]
    widths = [point[2] for point in profile]
    source_names = ", ".join(source.name for source in sources)
    text = f"""// Generated by support/build_entry_nominal.py from {source_names}.
// Energy height is altitude + airspeed^2 / (2*g0), expressed in metres.
global entry_nominal_energy_min is {ENERGY_MIN_M}.
global entry_nominal_energy_max is {ENERGY_MAX_M}.
global entry_nominal_range_max is {RANGE_MAX_M}.
global entry_nominal_energy_samples is {ks_list(energies)}.
global entry_nominal_range_samples is {ks_list(ranges)}.
global entry_nominal_corridor_samples is {ks_list(widths)}.

function entry_nominal_energy_height {{
    parameter altitude_, airspeed_.
    return altitude_+airspeed_*airspeed_/(2*9.81).
}}

function entry_nominal_range_at_energy {{
    parameter energy_height_.
    if energy_height_ <= entry_nominal_energy_samples[0] {{
        return entry_nominal_range_samples[0].
    }}
    local last_index is entry_nominal_energy_samples:length-1.
    if energy_height_ >= entry_nominal_energy_samples[last_index] {{
        return entry_nominal_range_samples[last_index].
    }}
    for profile_index in range(1, entry_nominal_energy_samples:length) {{
        local upper_energy is entry_nominal_energy_samples[profile_index].
        if energy_height_ <= upper_energy {{
            local lower_energy is entry_nominal_energy_samples[profile_index-1].
            local fraction is (energy_height_-lower_energy)/(upper_energy-lower_energy).
            local lower_range is entry_nominal_range_samples[profile_index-1].
            local upper_range is entry_nominal_range_samples[profile_index].
            return lower_range+(upper_range-lower_range)*fraction.
        }}
    }}
    return entry_nominal_range_samples[last_index].
}}
"""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text)


def image_x(energy_height: float) -> float:
    fraction = (energy_height - ENERGY_MIN_M) / (ENERGY_MAX_M - ENERGY_MIN_M)
    return PLOT_LEFT + max(0.0, min(1.0, fraction)) * (PLOT_RIGHT - PLOT_LEFT)


def image_y(remaining_range: float) -> float:
    fraction = max(0.0, min(1.0, remaining_range / RANGE_MAX_M))
    layout_y = PLOT_BOTTOM - fraction * (PLOT_BOTTOM - PLOT_TOP)
    return layout_y * IMAGE_HEIGHT / LAYOUT_HEIGHT


def write_image(path: Path, profile: list[tuple[float, float, float]]) -> None:
    scale = 3
    image = Image.new("RGBA", (IMAGE_WIDTH * scale, IMAGE_HEIGHT * scale), (0, 0, 0, 0))
    draw = ImageDraw.Draw(image, "RGBA")
    font = ImageFont.load_default(size=13 * scale)

    def point(x: float, y: float) -> tuple[int, int]:
        return round(x * scale), round(y * scale)

    upper = [point(image_x(energy), image_y(nominal + width)) for energy, nominal, width in profile]
    lower = [point(image_x(energy), image_y(nominal - width)) for energy, nominal, width in profile]
    center = [point(image_x(energy), image_y(nominal)) for energy, nominal, _ in profile]

    draw.polygon(upper + list(reversed(lower)), fill=(0, 255, 80, 28))
    draw.line(upper, fill=(0, 180, 60, 190), width=2 * scale, joint="curve")
    draw.line(lower, fill=(0, 180, 60, 190), width=2 * scale, joint="curve")
    draw.line(center, fill=(0, 255, 50, 255), width=3 * scale, joint="curve")

    for range_km in range(0, 1101, 200):
        y = image_y(range_km * 1000)
        draw.text(point(704, y - 6), str(range_km), font=font, fill=(0, 255, 50, 255))
    draw.text(point(665, image_y(RANGE_MAX_M) - 24), "RNG km", font=font, fill=(0, 255, 50, 255))

    bottom_y = image_y(0)
    for energy_km in (110, 150, 200, 250, 285):
        x = image_x(energy_km * 1000)
        draw.text(point(x - 12, bottom_y + 12), str(energy_km), font=font, fill=(0, 255, 50, 255))
    draw.text(point(322, bottom_y + 35), "ENERGY HEIGHT km", font=font, fill=(0, 255, 50, 255))

    image = image.resize((IMAGE_WIDTH, IMAGE_HEIGHT), Image.Resampling.LANCZOS)
    path.parent.mkdir(parents=True, exist_ok=True)
    image.save(path)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("flight_directories", type=Path, nargs="+")
    parser.add_argument(
        "--profile",
        type=Path,
        default=Path("Script/Libraries/Poseidon_SSTO/entry_nominal_profile.ks"),
    )
    parser.add_argument(
        "--image",
        type=Path,
        default=Path("Script/Libraries/gui_images/traj1_entry_nominal.png"),
    )
    args = parser.parse_args()

    curves = [load_curve(directory) for directory in args.flight_directories]
    profile = build_profile(curves)
    write_profile(args.profile, profile, args.flight_directories)
    write_image(args.image, profile)
    print(f"wrote {args.profile} and {args.image} from {len(curves)} flights")


if __name__ == "__main__":
    main()
