"""Precompute a small TEAM turn table from the local Poseidon FAR export.

Run from the repository root: python3 build_team_turn_table.py
The full FAR CSV remains a local calibration artifact; the generated .ks table
contains only clean-flight turn rates and drag for TEAM's candidate commands.
"""

from __future__ import annotations

import csv
import hashlib
import math
from pathlib import Path


ROOT = Path(__file__).resolve().parent
SOURCE = ROOT / "Script/POS_calibration/far.csv"
OUTPUT = ROOT / "Script/Libraries/Poseidon_SSTO/terminal_turn_table.ks"
ALTITUDES = (7000, 10500, 14000, 21000, 28000, 35000, 45500, 56000, 63000, 70000)
SPEEDS = (100, 200, 300, 500, 750, 1000, 1250, 1500)
AOAS = (12, 16, 20)
BANKS = (30, 45, 60)
CRAFT = "Poseidon SSTO Block 2.5"
GRAVITY = 3.5316e12 / 600000**2


def number(value: float) -> str:
    if abs(value) < 0.0000001:
        return "0"
    return format(value, ".5g")


def table_text(name: str, profiles: list[list[list[float]]]) -> str:
    lines = [f"global {name} is list("]
    for profile_index, rows in enumerate(profiles):
        lines.append("    list(")
        for row_index, values in enumerate(rows):
            ending = "," if row_index < len(rows) - 1 else ""
            lines.append("        " + ",".join(number(value) for value in values) + ending)
        ending = "," if profile_index < len(profiles) - 1 else ""
        lines.append("    )" + ending)
    lines.append(").")
    return "\n".join(lines)


def main() -> None:
    if not SOURCE.exists():
        raise SystemExit(f"Missing local FAR export: {SOURCE}")
    selected = {}
    with SOURCE.open(newline="", encoding="utf-8-sig") as stream:
        for row in csv.DictReader(stream):
            if (row["body"], row["craft_name"], row["configuration"]) != (
                "Kerbin", CRAFT, "clean"
            ):
                continue
            key = tuple(int(float(row[field])) for field in (
                "altitude_m", "speed_mps", "aoa_deg", "bank_deg"
            ))
            if key[0] in ALTITUDES and key[1] in SPEEDS and key[2] in AOAS and key[3] in BANKS:
                if key in selected:
                    raise ValueError(f"Duplicate FAR cell: {key}")
                selected[key] = (
                    float(row["force_right_kn"]),
                    float(row["force_top_kn"]),
                    float(row["force_forward_kn"]),
                )

    rate_profiles = []
    loss_profiles = []
    for aoa in AOAS:
        for bank in BANKS:
            rate_rows = []
            loss_rows = []
            alpha = math.radians(aoa)
            beta = math.radians(bank)
            for altitude in ALTITUDES:
                rates = []
                losses = []
                for speed in SPEEDS:
                    key = (altitude, speed, aoa, bank)
                    right, top, forward = selected[key]
                    # The export rotates relative wind around vessel forward.
                    # Project FAR force into horizontal turn and wind axes.
                    lateral_kn = -(right * math.cos(beta) + top * math.sin(beta))
                    drag_kn = -(
                        forward * math.cos(alpha)
                        + (-top * math.cos(beta) + right * math.sin(beta)) * math.sin(alpha)
                    )
                    if lateral_kn < 0 or drag_kn < 0:
                        raise ValueError(f"Invalid clean turn force at {key}: {lateral_kn}, {drag_kn}")
                    # kN / tonne = m/s^2. Runtime divides by live mass; no
                    # FAR calls, trig, or force-axis projections are needed.
                    rates.append(lateral_kn * (180 / math.pi) / speed)
                    losses.append(drag_kn / GRAVITY)
                rate_rows.append(rates)
                loss_rows.append(losses)
            rate_profiles.append(rate_rows)
            loss_profiles.append(loss_rows)

    digest = hashlib.sha256(SOURCE.read_bytes()).hexdigest()
    text = "\n".join((
        "// Generated by build_team_turn_table.py from the local FAR clean grid.",
        f"// Body: Kerbin. Craft: {CRAFT}. FAR CSV SHA-256: {digest}",
        "// Modes are AoA 12/16/20 degrees x relative bank 30/45/60 degrees.",
        "// Rate rows are turn-rate (deg/s) times mass (tonnes).",
        "// Loss rows are drag energy-height loss (m/m) times mass (tonnes).",
        "// Valid above 7 km at 100-1500 m/s; guidance uses a fallback outside this grid.",
        "global TEAM_TURN_ALTITUDES is list(" + ",".join(map(str, ALTITUDES)) + ").",
        "global TEAM_TURN_SPEEDS is list(" + ",".join(map(str, SPEEDS)) + ").",
        "global TEAM_TURN_AOAS is list(" + ",".join(map(str, AOAS)) + ").",
        "global TEAM_TURN_BANKS is list(" + ",".join(map(str, BANKS)) + ").",
        table_text("TEAM_TURN_RATE_MASS", rate_profiles),
        table_text("TEAM_TURN_LOSS_MASS", loss_profiles),
        "",
    ))
    OUTPUT.write_text(text)
    print(f"Wrote {OUTPUT.relative_to(ROOT)} from {len(selected)} FAR cells ({digest[:12]})")


if __name__ == "__main__":
    main()
