// Generated by support/build_entry_nominal.py from flight_244, flight_247, flight_248, flight_252, flight_253, flight_254, flight_256, flight_260, flight_265.
// Energy height is altitude + airspeed^2 / (2*g0), expressed in metres.
global entry_nominal_energy_min is 110000.0.
global entry_nominal_energy_max is 285000.0.
global entry_nominal_range_max is 1100000.0.
global entry_nominal_traj1_energy_min is 260000.0.
global entry_nominal_traj1_energy_max is 290000.0.
global entry_nominal_traj1_range_min is 600000.0.
global entry_nominal_traj1_range_max is 1100000.0.
global entry_nominal_traj2_energy_min is 210000.0.
global entry_nominal_traj2_energy_max is 260000.0.
global entry_nominal_traj2_range_min is 450000.0.
global entry_nominal_traj2_range_max is 800000.0.
global entry_nominal_traj3_energy_min is 170000.0.
global entry_nominal_traj3_energy_max is 210000.0.
global entry_nominal_traj3_range_min is 150000.0.
global entry_nominal_traj3_range_max is 600000.0.
global entry_nominal_traj4_energy_min is 140000.0.
global entry_nominal_traj4_energy_max is 170000.0.
global entry_nominal_traj4_range_min is 50000.0.
global entry_nominal_traj4_range_max is 300000.0.
global entry_nominal_traj5_energy_min is 100000.0.
global entry_nominal_traj5_energy_max is 140000.0.
global entry_nominal_traj5_range_min is 0.0.
global entry_nominal_traj5_range_max is 180000.0.
global entry_nominal_energy_samples is list(110000.0,115000.0,120000.0,125000.0,130000.0,135000.0,140000.0,145000.0,150000.0,155000.0,160000.0,165000.0,170000.0,175000.0,180000.0,185000.0,190000.0,195000.0,200000.0,205000.0,210000.0,215000.0,220000.0,225000.0,230000.0,235000.0,240000.0,245000.0,250000.0,255000.0,260000.0,265000.0,270000.0,275000.0,280000.0,285000.0).
global entry_nominal_range_samples is list(27549.923,25491.793,44020.954,61468.365,78263.548,94465.811,110897.388,127010.357,143834.726,161485.65,179436.677,196931.844,214558.361,233123.409,254855.587,282764.216,320697.908,371555.961,429904.596,481824.539,520737.888,549925.007,573116.411,592925.598,610542.738,626850.992,642494.153,658036.509,674045.562,691072.72,709695.157,731789.57,760164.847,800460.616,871551.613,1033334.981).
global entry_nominal_corridor_samples is list(50000.0,50000.0,50000.0,50000.0,50000.0,50000.0,50000.0,50000.0,50000.0,50000.0,50000.0,50000.0,50000.0,50000.0,50000.0,50000.0,56137.055,65373.387,66697.098,52678.669,50000.0,50000.0,50000.0,50000.0,50000.0,50000.0,50000.0,50000.0,50000.0,50000.0,50000.0,50000.0,50000.0,50000.0,50000.0,50108.725).

function entry_nominal_energy_height {
    parameter altitude_, airspeed_.
    return altitude_+airspeed_*airspeed_/(2*9.81).
}

function entry_nominal_range_at_energy {
    parameter energy_height_.
    if energy_height_ <= entry_nominal_energy_samples[0] {
        return entry_nominal_range_samples[0].
    }
    local last_index is entry_nominal_energy_samples:length-1.
    if energy_height_ >= entry_nominal_energy_samples[last_index] {
        return entry_nominal_range_samples[last_index].
    }
    for profile_index in range(1, entry_nominal_energy_samples:length) {
        local upper_energy is entry_nominal_energy_samples[profile_index].
        if energy_height_ <= upper_energy {
            local lower_energy is entry_nominal_energy_samples[profile_index-1].
            local fraction is (energy_height_-lower_energy)/(upper_energy-lower_energy).
            local lower_range is entry_nominal_range_samples[profile_index-1].
            local upper_range is entry_nominal_range_samples[profile_index].
            return lower_range+(upper_range-lower_range)*fraction.
        }
    }
    return entry_nominal_range_samples[last_index].
}
