// Generated by support/build_entry_nominal.py from flight_252, flight_253, flight_254.
// Energy height is altitude + airspeed^2 / (2*g0), expressed in metres.
global entry_nominal_energy_min is 110000.0.
global entry_nominal_energy_max is 285000.0.
global entry_nominal_range_max is 1100000.0.
global entry_nominal_energy_samples is list(110000.0,115000.0,120000.0,125000.0,130000.0,135000.0,140000.0,145000.0,150000.0,155000.0,160000.0,165000.0,170000.0,175000.0,180000.0,185000.0,190000.0,195000.0,200000.0,205000.0,210000.0,215000.0,220000.0,225000.0,230000.0,235000.0,240000.0,245000.0,250000.0,255000.0,260000.0,265000.0,270000.0,275000.0,280000.0,285000.0).
global entry_nominal_range_samples is list(5462.076,25242.385,43885.013,61030.507,77842.183,94063.966,110210.616,126616.517,143733.973,161485.65,179442.161,197164.612,214786.711,233320.021,255031.026,282764.216,320697.908,371555.961,429904.596,481824.539,520737.888,549925.007,573116.411,592925.598,610542.738,626850.992,642494.153,658036.509,674023.772,691025.502,709664.036,731763.127,760135.996,800454.271,871550.361,1033334.861).
global entry_nominal_corridor_samples is list(25000.0,25000.0,25000.0,25000.0,25000.0,25000.0,25000.0,25000.0,25000.0,25000.0,25000.0,25000.0,25000.0,25000.0,25000.0,25000.0,25000.0,25000.0,25000.0,25000.0,25000.0,25000.0,25000.0,25000.0,25000.0,25000.0,25000.0,25000.0,25000.0,25000.0,25000.0,25000.0,25000.0,25000.0,25000.0,25000.0).

function entry_nominal_energy_height {
    parameter altitude_, airspeed_.
    return altitude_+airspeed_*airspeed_/(2*9.81).
}

function entry_nominal_range_at_energy {
    parameter energy_height_.
    if energy_height_ <= entry_nominal_energy_samples[0] {
        return entry_nominal_range_samples[0].
    }
    local last_index is entry_nominal_energy_samples:length-1.
    if energy_height_ >= entry_nominal_energy_samples[last_index] {
        return entry_nominal_range_samples[last_index].
    }
    for profile_index in range(1, entry_nominal_energy_samples:length) {
        local upper_energy is entry_nominal_energy_samples[profile_index].
        if energy_height_ <= upper_energy {
            local lower_energy is entry_nominal_energy_samples[profile_index-1].
            local fraction is (energy_height_-lower_energy)/(upper_energy-lower_energy).
            local lower_range is entry_nominal_range_samples[profile_index-1].
            local upper_range is entry_nominal_range_samples[profile_index].
            return lower_range+(upper_range-lower_range)*fraction.
        }
    }
    return entry_nominal_range_samples[last_index].
}
